---
title: "Guidelines for Nutrition Support with Refeeding Syndrome"
output: github_document
---

# Guidelines for Nutrition Support with Refeeding Syndrome 

## Introduction

Refeeding syndrome is a term used to describe metabolic and clinical changes that occur with the rapid reintroduction of nutrition for patients in a starved state.

The goal of these guidelines is to help clinicians identify patients at risk for refeeding syndrome, and to prevent and treat refeeding syndrome.

## Complications of Electrolyte Abnormalities

To understand the pathophysiology of refeeding syndrome, knowledge of metabolic changes in starvation is needed. Liver glycogen is depleted within 24 hours when fasting. Insulin secretion decreases and glucagon secretion increases. In the starved state, the body uses primarily fat and protein for energy. Gluconeogenesis provides some glucose during the first 7 days of starvation but then decreases to preserve lean body mass. In prolonged starvation, fatty acids are the primary source of energy as the brain shifts from using glucose to using ketone bodies for energy. Some intracellular minerals (i.e. phosphate) are depleted but serum concentrations remain normal because the intracellular compartment contracts and renal excretion of these minerals decreases.

For patients who have metabolically adapted to starvation, the reintroduction of nutrients, particularly carbohydrates, causes four major changes in macronutrient metabolism: 1) insulin secretion increases, 2) glucagon secretion is inhibited 3) previously diminished anabolic pathways are activated, and 4) a shift from lipolysis to lipogenesis occurs. Though these changes occur normally in all patients, these changes increase refeeding syndrome risk particularly in starved patients, who have reduced ATP availability, reduced whole-body stores of electrolytes and vitamins, and diminished physiologic reserves to tolerate insults. In starved patients, insulin stimulates the intracellular shift of phosphate, magnesium, thiamine, and potassium for glycogen, fat, and protein synthesis. This leads to hypophosphatemia, hypomagnesemia, hypokalemia, and thiamine deficiency. Glucocorticoid circulation increases and can lead to hyperglycemia. Resulting hyperinsulinemia leads to decreased renal excretion of sodium and water. Sodium and water retention causes an expansion of fluid compartments.

## Signs/symptoms of Refeeding Syndrome:

Weakness (electrolyte abnormalities such as hypophosphatemia)

- Arrhythmia (hypomagnesaemia and hypokalemia)
- Heart failure (fluid overload, malnutrition, and hypokalemia)
- Respiratory issues (hypophosphatemia, fluid overload, and carbon dioxide retention)
- Neurological defects such as Wernicke's encephalopathy (thiamine deficiency)
- Anemia (increased red blood cell lysis, hypomagnesemia)
- Increased infection risk (immunologic dysfunction, hyperglycemia)

--- page 1 ---

# Patients at Risk for Refeeding Syndrome

|  Adults @ Risk for Refeeding Syndrome | Moderate Risk: 2 criteria needed | Significant Risk: 1 criteria  |
| --- | --- | --- |
|  Body Mass Index (BMI) | 16-18.5 kg/m² | <16 kg/m²  |
|  Wt loss | 5% in 1 month | 7.5% in 3 mos or >/=10% in 6 mos  |
|  Caloric Intake | None/negligible PO x 5-6d OR <75% EER >7d during acute illness or injury OR <75% EER for >1 month | None/negligible PO >7d OR <50% of EER for >5d during acute illness or injury OR 50% of EER for >1 month  |
|  Abnormal prefeeding K+, phos, or magnesium serum concentrations | Low levels OR normal current levels AND recent low levels necessitating minimal or single-dose supplementation | Critically low levels OR Borderline low/normal levels AND recent low levels necessitating significant or multiple-dose supplementation  |
|  Loss of subcutaneous fat | Evident moderate loss | Evident severe loss  |
|  Loss of muscle mass | Evident moderate loss | Evident severe loss  |
|  Higher risk comorbidities | See list below | See list below  |

Minimally adapted from: ASPEN, American Society for Parenteral and Enteral Nutrition, Refeeding Consensus Guidelines 2020.

Other patients who may be at risk for refeeding: - Abused/neglected adults - Advanced age - Anorexia Nervosa - Alcoholism, Substance abuse - Dysphagia - Food insecurity - HIV/AIDS - Inadequate EN or PN > 10 days - Decompensated liver failure - Malabsorption (SBS, IBD, CF, chronic pancreatitis, bariatric surgery, significant small bowel resection) - Malignancy - Advanced neurological impairment - NPO/clears >5-7d - Persistent N/V/D - Uncontrolled diabetes mellitus (/DKA)

Recommendations for Initiation and Advancement of Nutrition Support in the Inpatient Setting

Prior to starting Nutrition Support: 1) Check baseline electrolytes (K,Phos, Mg) and initiate IV repletion where needed 2) Start Vitamins: Daily MVI and 200 mg of Thiamine/day x 10 days

--- page 2 ---

# Initiating Nutrition Support

**Day 1:** continuous rate (DO NOT cycle/bolus)

- 10-20 kcal/kg/day
- Dextrose 100-150 gm/day
- Limit fluids to 1000-1500 mL for step/day 1; may disregard fluid restriction if patient is tolerating >1000 mL/d fluids prior to starting nutrition support
  - particularly small patients may need lower/more tailored volume calculations
- When concentrating fluids in TPN consider limitations with macronutrients, electrolytes, micronutrients, and compatibility
- OK to give full amount of protein and fat if adhering to kcal restrictions as above
- Review dosage and duration of dextrose-containing medications and IVF given prior to TF/TPN
  - Adjust recommendations accordingly
  - if patient is receiving 100-150 gm CHO vs 10-20 kcal/kg already and lytes, BG WNL, can skip step/day 1 feeding recommendations, depending on patient’s nutrient needs and risk level
  - Discontinue dextrose-containing IVF once feeding initiated

# Subsequent days, increase in step-wise manner

- Increase carbohydrate (+ kcal, if possible) 33%/day = ideally, advance over 3 days.
- For significant risk and/or with very high calorie needs, may need longer advancement
- For moderate risk or receiving dextrose-containing IVF and stable, may advance more quickly

**PO:** ad lib and encourage slow advancement of carbohydrates, monitor for signs/symptoms of refeeding syndrome

# Monitoring and Repletion

## Electrolytes:

- Monitor electrolytes (Na, potassium, magnesium, phosphorus) BID for first 3d of feeding
- then daily until stable/uptrending
- then 3x/week for subsequent weeks
- Replete IV

# Daily Baseline Phosphorus Requirements for Adult PN formulations

These are baseline phosphorus electrolyte requirements without refeeding syndrome risk. Consider patients at risk for refeeding syndrome will require these quantities at minimum and likely more for at least the first 3 days of TPN titration toward macronutrient goal.

|  Phosphate | 20 to 40 mMol/d  |
| --- | --- |
|  |   |

If serum phos < 1.8 mg/dL: Continue nutrition support at same rate and replete phosphorus. Do not advance nutrition support until serum phosphorus is >/= 1.8 mg/dL.

If serum phos and/or potassium critically low, reduce TF/TPN rate by 50% and replete aggressively. Do not advance nutrition support until serum phos >/= 1.8 mg/dL. For patients refractory to high dose

--- page 3 ---

repletion while feeding, may need to reduce feeding rate and/or carbohydrate delivery another 50% until lytes stabilize/uptrend.

*Patients with impaired renal function may initially have normal/high electrolytes and decrease over time after initiation of nutrition--“late refeeding.”

**Blood Sugar**

- Proactively manage blood sugar; achieve glycemic control before advancing TPN dextrose concentrations.

**Fluids:** monitor daily fluid status via daily weights, I/Os
- Order daily weights and strict I/Os x first 3d of feeding

Continue to monitor for signs/symptoms of refeeding syndrome (see section on Complications of Electrolyte Abnormalities)

**Documentation:**

Use Smartphrases .NUTREFEEDSYNDROMEASSESS and .NUTREFEEDSYNDROMERECS

**For Refeeding Syndrome Patients On the Weekend:**

- Service-line RDs concerned about significant risk refeeding patients will liaise with primary team and Pharmacy on Friday to sign out nutrition plan (vit/min, lyte checks, and nutrition support regimen).

Service line RD will provide comprehensive advancement recs in a pre-weekend note

**For Refeeding Syndrome Patients in the Ambulatory Setting:**

- Service-line RDs concerned about at-risk refeeding patients will liaise with the primary team signing nutrition orders to sign out nutrition plan (vitamin/mineral, electrolyte checks, and nutrition support regimen).

- The following recommendations for initiation and advancement are guidelines, however patients at risk for refeeding syndrome in the ambulatory setting are best treated in the inpatient setting and should be admitted.

**Recommendations for Initiation and Advancement of Nutrition Support in the Ambulatory Setting:**

**For patients at Significant risk for refeeding,**

- Direct admission is highly recommended for close electrolyte monitoring, initiation, and advancement of nutrition support.

- Consult the inpatient dietitian to monitor the patient through nutrition support advancement

**For patients at Moderate Risk for refeeding:**

**Prior to feeding tube placement or start of TF/TPN:**

1) Check baseline electrolytes (K,Phos, Mg) and provide repletion.
2) Once electrolytes stable, consider conservative initiation of tube feeding.
3) Start Vitamins: Daily MVI and 200 mg of Thiamine/day x 10 days

**Initiating Nutrition Support**


MNKOI 0000816658

--- page 4 ---

Day 1: infuse half carton of formula for each bolus feed or initiate continuous feeding at a low rate (less or equal to $20 \mathrm{ml} / \mathrm{hr}$ ) with maximum dosages listed below. If patient to initiate total parenteral nutrition (TPN), recommend close adherence to the below guideline recommendations and close communication with home infusion provider pharmacist and dietitian.

- $10-20 \mathrm{kcal} / \mathrm{kg} /$ day
- Dextrose 100-150 gm/day
- Limit fluids to 1000-1500mL for step/day 1; may disregard fluid restriction if patient is tolerating $>1000 \mathrm{~mL} / \mathrm{d}$ fluids prior to starting nutrition support
- particularly small patients may need lower/more tailored volume calculations
- Review dosage and duration of dextrose-containing medications and IVF given prior to TF/TPN
- Adjust recommendations accordingly
- if patient is receiving $100-150 \mathrm{gm} \mathrm{CHO}$ vs $10-20 \mathrm{kcal} / \mathrm{kg}$ already and electrolytes, BG WNL, can skip step/day 1 feeding recommendations, depending on patient's nutrient needs and risk level
- If applicable, discontinue dextrose-containing IVF once feeding initiated


# Subsequent days, increase in step-wise manner 

- Increase carbohydrate (+ kcal, if possible)-by 33\% of goal every 1-2 days
- For tube feeding, Increase to full carton of formula for feeds on day 2 of feeding.


## Monitoring and Repletion

## Electrolytes:

- Treatment team to:
- Monitor electrolytes (have standing orders for CMP, magnesium and phosphorus) the day after initiation of feeds and replete electrolytes if needed
- If there is a critical level for CMP, magnesium, or phosphorus, the patient may require IV repletion, which requires a visit to urgent care or the emergency department.
- If electrolytes were replaced, recheck labs the next day. /Check electrolytes 3x/week, or until stable. If this is not feasible, the patient should be admitted for electrolyte repletion and monitoring for signs and symptoms of refeeding syndrome.
- If electrolytes become difficult to correct or drop precipitously during the initiation of nutrition, decrease grams of dextrose to $50 \%$ for TPN patients. For enteral nutrition, reduce volume of formula provided to patient. Once stable, advance dextrose by $\sim 33 \%$ of goal every 1-2 days based on clinical presentation.
- If patient cannot have labs checked, cannot monitor for symptoms of refeeding, and/or it is difficult to monitor symptoms due to other conditions, patient should be admitted.

Fluids: RN to monitor fluid status via weights in clinic and have patient check daily weight at home
Continue to monitor for signs/symptoms of refeeding syndrome (see section on Complications of Electrolyte Abnormalities)

## Documentation:

Use Smartphrases .NUTOPREFEEDSYNDROMEASSESS and .NUTOPREFEEDSYNDROMERECS

--- page 5 ---

References:

Boullata, J., Brantley, S., Corkins, M., Guenter, P., Krenitsky, J., Lyman, B., ... Wessel, J. (2009). Enteral Nutrition Practice Recommendations. Journal of Parenteral and Enteral Nutrition, 33(2), 122-167.

Byrnes, M.C., Stangenes, J. (2011). Refeeding in the ICU: an adult and pediatric problem. CurrOpinClinNutrMetab Care, 14(2), 186-192.

Coram. Refeeding Syndrome: The Silent Killer [PowerPoint Slides].

Da Silva et al. (2020). ASPEN Consensus Recommendations for Refeeding Syndrome. NCP 35(2), 178-195.

Gentile M.G., Pastorelli, P., Ciceri, R., Manna, G.M., Collimediglia, S. (2010). Specialized refeeding treatment for anorexia nervosa patients suffering from extreme undernutrition. Clinical Nutrition, 29(5), 627-32.

Kirkland, L., Kashiwagi, D.T., Brantley, S., Scheurer, D., Varkey, P. (2013). Nutrition in the Hospitalized Patient. Journal of Hospital Medicine, 8(1), 52-58.

McCray, S., Walker, S., Parrish, C.R. (2005). Much Ado About Refeeding. Practical Gastroenterology, 23(12), 26-44.

McKnight et al. Refeeding Syndrome in the Critically Ill: A Literature Review and Clinician’s Guide. Curr Gastroenterol Rep. 2019 Nov 22;21(11):58.

Mehanna, H., Moledina, J., Travis, J. (2008). Refeeding syndrome: what it is, and how to prevent and treat it. BMJ, 336(7659), 1495-1498.

Mehler, P.S., Crews, C.K. (2001). Refeeding the Patient With Anorexia Nervosa. Eating Disorders, 9(2), 167-171.

Mirtallo, J., Canada, T., Johnson, D., Kumpf, V., Petersen, C., Sacks, G., ... Guenter, P. (2004). Safe Practices for Parenteral Nutrition. Journal of Parenteral and Enteral Nutrition, 28(6), s39-s70.

National Institute for Health and Clinical Excellence. (2006). Nutrition support in adults. Clinical Guideline 32.

Skipper, A. (2012). Refeeding Syndrome or Refeeding Hypophosphatemia: A Systematic Review of Cases. NutrClinPract, 27(1), 34-40.

Zeki, S., Culkin, A., Gabe, S.M., Nightingale, J.M. (2011). Refeeding hypophosphatemia is more common in enteral than parenteral feeding in adult patients. Clinical Nutrition, 30(3), 365-368.

Parrish CR, McCray, S. (2016). Refeeding the Malnourished Patient: Lessons Learned. Practical Gastroenterology, 155, 56, 58-66.

Citations for phos repletion:

Kraft MD, Btaiche IF, Sacks GS, Kudsk KA. Treatment of electrolyte disorders in adult patients in the intensive care unit. Am J Health Syst Pharm 2005; 62:1663.

Taylor BE, Huey WY, Buchman TG, et al. Treatment of hypophosphatemia using a protocol based on patient weight and serum phosphorus level in a surgical intensive care unit. J Am Coll Surg 2004; 198:198.

Subramanian R, Khardori R. Severe hypophosphatemia. Pathophysiologic implications, clinical presentations, and treatment. Medicine (Baltimore) 2000; 79:1.

Brown KA, Dickerson RN, Morgan LM, et al. A new graduated dosing regimen for phosphorus replacement in patients receiving nutrition support. JPEN J Parenter Enteral Nutr 2006; 30:209.

--- page 6 ---

Weisinger JR, Bellorín-Font E. Magnesium and phosphorus. Lancet 1998; 352:391.
Bruno J, Canada T, Canada N, Tucker AM, Ybarra JV. ASPEN Fluids, Electrolytes, and Acid-Base Disorders Handbook, $2^{\text {nd }}$ Edition. (ASPEN) 2020; 149.

Created: 4/2013 JD, JS, QS, JW
Updated 2/2018 QS, JB, AW, MM, LC
Updated 8/2021 MC, RM, KM, KC, BP
Updated 9/2023 KM, ND, QS